
services:
  #MongoDB services
  mongo_db:
    container_name: db_conatiner
    image: mongo:latest
    restart: always #if the constainer fails at some point of time in the future it should restart
    volumes:
    - mongo_db:/data/db
    ports:
      - "27017:27017"

  #Node API Service
  api:
    build: .
    ports:
      - 3016:3016
    environment:
      NODE_ENV: "development"
      LISTEN_IP: '0.0.0.0'
      PORT: '3016'
      CLIENT_URL: 'http://localhost:3016'
      # Set your database/API connection information here
      DATABASE_DEV_URL: 'mongodb://mongo_db:27017/buchi'
      DATABASE_TEST_URL: 'mongodb://mongo_db:27017/buchi_test'
      # DATABASE_PROD_URL=<insert_URI_to_prod_db>

    depends_on:
      - mongo_db #specify the service name in which the localupper service depends
volumes: 
  mongo_db:
